### ISSUE TITLE
Recently opened files menu

### ISSUE THREAD

**Issue by skoslowski** [gnuradio/gnuradio-wg-grc#30]
Add a list of recently opened files to the File menu.

- new combined getter/setter in Preferences.py like files_open
- keep track of recently opened files in MainWindow (open, save as) and save to prefs
- update Menu on change (much like File->New)

@glennlive, would you be interested in implementing that?

**Comment by glennlive** [comment]
As long as I can be helpful and find time.  :)

I suppose the recent files list should be separate from the open files tabs... How many do you want to show (say the five most recently closed)?

Where is the best place to suggest new features or flesh out details of current ones?  Do you use the issue tracker or wiki or just email??
